[package]
name = "ulid"
version = "0.1.0"
authors = ["dylanhart <dylan96hart@gmail.com>"]

description = "a Universally Unique Lexicographically Sortable Identifier implementation"
keywords = ["ulid", "uuid", "sortable", "identifier"]

[dependencies]
byteorder = "1.0.0"
chrono = "0.3"
lazy_static = "0.2.8"
rand = "0.3"
