[package]
name = "ulid"
version = "0.1.2"
authors = ["dylanhart <dylan96hart@gmail.com>"]

license = "MIT"
readme = "README.md"

description = "a Universally Unique Lexicographically Sortable Identifier implementation"
keywords = ["ulid", "uuid", "sortable", "identifier"]

repository = "https://github.com/dylanhart/ulid-rs"

[dependencies]
chrono = "0.3"
lazy_static = "0.2"
rand = "0.3"

[dev-dependencies]
bencher = "0.1"

[[bench]]
name = "bench"
path = "benches/bench.rs"
harness = false
