name: ci-build
on: [push]
jobs:
  do-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo test
      - run: cargo test --all-features
      - run: cargo test --no-default-features

